---
- name: "Pull Docker image for joeschr/freqtrade-trades:latest from Registry."
  community.docker.docker_image:
    name: joeschr/freqtrade-trades
    tag: "latest"
    source: pull
  when: not build_freqtrade|bool
