---
- name: "Docker custom image tasks."
  block:
    - name: "create Dockerfile for {{ freqtrade_custom_prefix }}/freqtrade:{{ freqtrade_branch }}."
      template:
        src: "Dockerfile.j2"
        dest: "{{ docker_build_directory }}/freqtrade-custom/Dockerfile"

    - name: "Build Docker image for {{ freqtrade_custom_prefix }}/freqtrade:{{ freqtrade_branch }}."
      community.docker.docker_image:
        name: "{{ freqtrade_custom_prefix }}/freqtrade"
        tag: "{{ freqtrade_branch }}"
        build:
          dockerfile: "{{ docker_build_directory }}/freqtrade-custom/Dockerfile"
          path: "{{ docker_build_directory }}/freqtrade-custom"
        source: build

  when: build_freqtrade_custom|bool and freqtrade_custom_prefix is defined and (freqtrade_custom_commands is iterable or freqtrade_custom_pips is iterable)